### PR TITLE
'race' mode

### PR DESCRIPTION
**Pull request by ItzBlack6093**
...why xd, just a mode with tgm's leveling system
[what i have done so far](https://www.youtube.com/watch?v=D_m5Ftd0tLY)

### CODE REVIEW

**Comment by ItzBlack6093** [comment]
misclicked

**Comment by TitanPlayz100** [comment]
Ok looks fine, maybe in the future can add a grading system

**Comment by ItzBlack6093** [comment]
Still considering which grading system I should use

- Score-Based (TGM1)
- Internal Grade (TAP & TI)

**Comment by TitanPlayz100** [comment]
tgm3 TI grading system feels much more interesting with all the extra stuff, but the problem is that game settings don't change for any game modes (maybe that can change) so that the game gets harder and grades are much cooler

- idea for later, add a separate toggle for competitive play where game settings are fixed to certain settings for each gamemode so that stuff like grading can be more important

**Comment by ItzBlack6093** [comment]
A quick example of the grading system

https://github.com/user-attachments/assets/a4e88ff4-69bf-45d5-99a4-29f9c013ade8

(starting with 30 grade boosts)

**Comment by TitanPlayz100** [comment]
Ye that looks pretty good. I don't know the grading mechanic too much so ur kinda on ur own with this but looks fine except the menu can definately be cleaned up with some subtexts

**Comment by ItzBlack6093** [comment]
bump because the game have competitive play feature

should i set the gamemode's gravity to 20g?

**Comment by TitanPlayz100** [comment]
yes i made competitive mode specifically for this

**Comment by ItzBlack6093** [comment]
ok i will create another pull request (maybe)

**Comment by ItzBlack6093** [comment]
one more gamemode is fine, isn't it?

**Comment by TitanPlayz100** [comment]
yes that would be pretty cool

**Comment by ItzBlack6093** [comment]
oke
feel free to pull anything you want and then i will add the gamemode later

_i have a zenith.js file for everything i need xd_

**Comment by TitanPlayz100** [comment]
You can make a new pr for zenith mode where i can do the merge resolutions

**Comment by ItzBlack6093** [comment]
```js
speedTable = // 1 / 65536 G
    {
        0:1024,
        30:1536,
        35:2048,
        40:2560,
        50:3072,
        60:4096,
        70:8192,
        80:12288,
        90:16384,
        100:20480,
        120:24576,
        140:28672,
        160:32768,
        180:36864,
        200:1024,
        220:8192,
        230:16384,
        233:24576,
        236:32768,
        239:40960,
        243:49152,
        247:57344,
        251:65536,
        300:131072,
        330:196608,
        360:262144,
        400:327680,
        420:262144,
        450:196608,
        500:1310720
    }

```

**Pull request merged**
